### ISSUE TITLE
23.40.2: build failure with glibc 2.43

### ISSUE THREAD

**Issue by tgurr** [greenbone/openvas-scanner#2138]
### Expected behavior
Do not fail to build with glibc 2.43.

### Actual behavior
```
[...]
[ 28%] Building C object nasl/CMakeFiles/openvas_nasl_shared.dir/exec.c.o
cd /var/tmp/paludis/build/net-analyzer-openvas-scanner-23.40.2/work/build/nasl && /usr/bin/x86_64-pc-linux-gnu-cc -DHAVE_LIBKSBA -DHAVE_NETSNMP -DOPENVASLIB_VERSION=\"23.40.2\" -DOPENVAS_CONF=\"/etc/openvas/openvas.conf\" -DOPENVAS_FEED_LOCK_PATH=\"/var/lib/openvas/feed-update.lock\" -DOPENVAS_GPG_BASE_DIR=\"/etc/openvas\" -DOPENVAS_NASL_VERSION=\"23.40.2\" -DOPENVAS_STATE_DIR=\"/var/lib/openvas\" -DOPENVAS_SYSCONF_DIR=\"/etc/openvas\" -Dopenvas_nasl_shared_EXPORTS -I/usr/x86_64-pc-linux-gnu/include/glib-2.0 -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include -I/usr/x86_64-pc-linux-gnu/include/json-glib-1.0 -I/usr/x86_64-pc-linux-gnu/include/libmount -I/usr/x86_64-pc-linux-gnu/include/blkid -I/usr/x86_64-pc-linux-gnu/include/gvm -I/usr/x86_64-pc-linux-gnu/include/uuid -pipe -O2 -march=native -D_FILE_OFFSET_BITS=64 -DLARGEFILE_SOURCE=1                                 -std=c11                                 -Wall                                 -Wextra                                 -Werror                                 -Wpedantic                                 -Wmissing-prototypes                                 -Wshadow                                 -Wsequence-point                                 -D_BSD_SOURCE                                 -D_ISOC11_SOURCE                                 -D_SVID_SOURCE                                 -D_DEFAULT_SOURCE -Wall -Wextra -fno-strict-aliasing -O3 -DNDEBUG -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -fPIC -fdiagnostics-color=always -MD -MT nasl/CMakeFiles/openvas_nasl_shared.dir/exec.c.o -MF CMakeFiles/openvas_nasl_shared.dir/exec.c.o.d -o CMakeFiles/openvas_nasl_shared.dir/exec.c.o -c /var/tmp/paludis/build/net-analyzer-openvas-scanner-23.40.2/work/openvas-scanner-23.40.2/nasl/exec.c
/var/tmp/paludis/build/net-analyzer-openvas-scanner-23.40.2/work/openvas-scanner-23.40.2/nasl/exec.c: In function 'exec_nasl_script':
/var/tmp/paludis/build/net-analyzer-openvas-scanner-23.40.2/work/openvas-scanner-23.40.2/nasl/exec.c:1722:9: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 1722 |       p = strrchr (name, '/');
      |
```

See: https://sourceware.org/glibc/wiki/Release/2.43#C23_Const-Preserving_Standard_Library_Macros_May_Break_Some_Packages

### Steps to reproduce
1. install/upgrade to glibc 2.43
2. try to build openvas-scanner 23.40.2

### Environment
**GCC**: 14.3.0
**Operating system:** Exherbo Linux
**Installation method / source:** source-based packages

### Logfiles
Complete build log: [openvas-scanner-23.40.2_build.log](https://github.com/user-attachments/files/25432355/openvas-scanner-23.40.2_build.log)

**Comment by tgurr** [comment]
While gvm-libs has been fixed by https://github.com/greenbone/gvm-libs/pull/1052 the latest openvas-scanner from today 23.40.3 is still unable to build with glibc 2.43. No idea if this is the correct approach but the following patch allows me to compile openvas-scanner 23.40.3: [openvas-scanner-23.40.3-glibc-2.43.patch](https://github.com/user-attachments/files/25689186/openvas-scanner-23.40.3-glibc-2.43.patch)
